spring.datasource.url=jdbc:postgresql://localhost:5432/bank_api
spring.datasource.username=bank_user
spring.datasource.password=bankpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

server.port=8081

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration=7d